name: Lux
version: ${project.version}
main: dev.bodner.jack.lux.Lux
api-version: 1.16
authors: [ Eilux ]
description: Server stuff
website: jack.bodner.dev
commands:
  ghost:
    description: Makes the player invisible and fakes a logoff
    usage: /<command>
    permission:

  pvp:
    description: Enables and disables PVP for the user
    usage: /<command>
    permission:

  setpvp:
    description: Sets if a player has PVP enabled
    usage: /<command> on|off <name>